import { DemoShell } from "../components/demo-shell";
import { ProceduralObject } from "../components/procedural-object";

export default function Home() {
  return <>
    <section className="intro-page">
      <header className="intro-nav"><span className="intro-logo">RL<span>.</span></span><span>SOFTWARE ENGINEER · CREATIVE TECHNOLOGIST</span><a href="#work">Work</a><a href="#about">About</a><a href="/ruoya-portfolio.pdf" target="_blank" rel="noreferrer">Resume ↗</a><a href="https://github.com" target="_blank" rel="noreferrer">GitHub ↗</a></header>
      <div className="intro-hero"><div><p className="eyebrow">Software Engineer</p><h1>Building software at the intersection of<br/><em>AI × 3D × creative technology.</em></h1><p className="hero-support">I build production applications, AI-powered tools, and interactive 3D systems.</p><div className="hero-actions"><a className="demo-cta" href="#work">View projects <span>↓</span></a><a className="hero-text-link" href="/ruoya-portfolio.pdf" target="_blank" rel="noreferrer">Resume ↗</a></div></div><ProceduralObject /></div>
      <div className="intro-divider"/>
      <div id="about" className="about-strip"><div><p className="eyebrow">About me</p><h2>Ruoya Li</h2></div><p>I build software that makes complex systems understandable and usable — from AI-assisted media workflows to data-informed product experiences.</p><a className="outline-cta" href="#portfolio-pdf">View selected work ↗</a></div>
      <section id="work" className="project-roadmap"><p className="eyebrow">Selected work</p><div className="project-line active"><span>01</span><div><h2>DramaClips / DramoraAI</h2><p>Production AI · Full-stack workflow system · <a href="#interactive-demo">Explore demo ↗</a></p></div><b>Current focus</b></div><div className="project-line"><span>02</span><div><h2>3D + Coding flagship</h2><p>AI-assisted computational 3D system</p></div><b>Coming soon</b></div><div className="project-line"><span>03</span><div><h2>Computational Design / Robotics</h2><p>Existing work collected in the portfolio PDF</p></div><b><a href="#portfolio-pdf">View PDF ↗</a></b></div></section>
      <div className="intro-grid"><div><p className="eyebrow">Featured system</p><h2>DramaClips</h2><p className="intro-copy">An AI-assisted short-drama content platform connecting source media, hook generation, publishing operations, and audience signals in one workflow.</p></div><div className="intro-facts"><div><small>ROLE</small><b>Product engineer<br/>System designer</b></div><div><small>FOCUS</small><b>Applied AI<br/>Workflow orchestration</b></div><div><small>STACK</small><b>Next.js · TypeScript · Python<br/>Supabase · R2 · Railway</b></div></div></div>
      <div className="admin-preview"><div><p className="eyebrow">Operator workspace</p><h2>From source<br/><em>to signal.</em></h2><p>One workspace for selecting episodes, generating explainable hooks, reviewing assets, and preparing distribution.</p><a className="demo-cta" href="#interactive-demo">Try the full workflow <span>↓</span></a></div><div className="admin-mock"><div className="mock-sidebar"><b>DramaClips</b><span>01 · Drama library</span><span className="mock-active">02 · Hook Studio</span><span>03 · Publish Center</span><span>04 · Analytics</span></div><div className="mock-content"><small>BUILT-IN GENERATION</small><strong>Create hooks</strong><div className="mock-row"><span>Revenge of the Black Swan</span><b>3/10 generated</b></div><div className="mock-cards"><i/><i/><i/><i/></div><div className="mock-button">Generate &amp; auto-save</div></div></div></div>
      <div className="intro-stack"><p className="eyebrow">Technology surface</p><div><span>Java</span><span>Python</span><span>TypeScript</span><span>React</span><span>Next.js</span><span>LLM APIs</span><span>Three.js</span><span>SQL</span><span>Faster-Whisper</span><span>FFmpeg</span></div></div>
    </section>
    <section id="interactive-demo" className="demo-section"><div className="demo-section-intro"><p className="eyebrow">01 / Interactive case study</p><h2>See how a hook<br/><em>gets selected.</em></h2><p>Complete the prepared workflow below. The processing log and scoring explanation mirror the production pipeline.</p></div><DemoShell /></section>
    <section id="portfolio-pdf" className="pdf-section"><div><p className="eyebrow">03 / Computational design &amp; robotics</p><h2>More work, <em>page by page.</em></h2><p>Browse the existing portfolio after exploring the DramaClips system.</p><a className="outline-cta" href="/ruoya-portfolio.pdf" target="_blank" rel="noreferrer">Open PDF in new tab ↗</a></div><div className="pdf-frame"><iframe src="/ruoya-portfolio.pdf#page=1&view=FitH" title="Ruoya Li portfolio PDF" /></div></section>
  </>;
}
