"use client";
import { useEffect, useState } from "react";

type Tab = "library" | "hooks" | "publish" | "analytics";
type Stage = "idle" | "queued" | "transcribing" | "analyzing" | "ranking" | "rendering" | "review_ready";
const nav: Array<[Tab, string]> = [["library", "Drama library"], ["hooks", "Hook Studio"], ["publish", "Publish Center"], ["analytics", "Analytics"]];
const stages: Array<[Stage, string]> = [["queued", "Queued"], ["transcribing", "Transcribing · Faster-Whisper"], ["analyzing", "Analyzing scenes · PySceneDetect"], ["ranking", "Ranking candidates"], ["rendering", "Rendering · FFmpeg"], ["review_ready", "Review ready"]];
const scores = [["Visual quality", "0.91", "35%"], ["Dialogue", "0.92", "10%"], ["Conflict", "0.86", "10%"], ["Tension", "0.81", "10%"], ["Cliffhanger", "0.78", "10%"], ["Reversal", "0.75", "8%"], ["Direction match", "0.88", "dynamic"]];
const clips = [
  "https://pub-65eeb3b6ecc44720ba440ea8c8454185.r2.dev/dramas/creation-itself-is-love/social/hooks/1f041d08-5179-43bc-b8c5-9abcedde83d8-What-happens-next-is-shocking.mp4",
  "https://pub-65eeb3b6ecc44720ba440ea8c8454185.r2.dev/dramas/crowned-in-silver-blood/social/hooks/02f95857-faf4-43be-b7ed-a145c015b7fe-She-finally-calls-him-out.mp4",
  "https://pub-65eeb3b6ecc44720ba440ea8c8454185.r2.dev/dramas/rising-from-theashes-i-cut-all-blood-ties/social/hooks/c26d14de-a0aa-4db5-9b79-62cfb0ff6811-She-finally-calls-him-out.mp4",
];

export function DemoShell() {
  const [tab, setTab] = useState<Tab>("library"); const [modal, setModal] = useState<string | null>(null); const [step, setStep] = useState(1); const [selected, setSelected] = useState([1, 2, 3]); const [stage, setStage] = useState<Stage>("idle"); const [generated, setGenerated] = useState(false); const [approved, setApproved] = useState(false); const [published, setPublished] = useState(false); const [added, setAdded] = useState(false); const [analytics, setAnalytics] = useState<{ mode: string; updatedAt: string; metrics: Record<string, number>; daily: number[] } | null>(null);
  useEffect(() => { fetch("/api/analytics").then((r) => r.json()).then(setAnalytics).catch(() => setAnalytics(null)); }, []);
  const generate = async () => { if (!selected.length || (stage !== "idle" && stage !== "review_ready")) return; setGenerated(false); setApproved(false); setStage("queued"); for (const next of ["transcribing", "analyzing", "ranking", "rendering"] as Stage[]) { await new Promise((r) => window.setTimeout(r, 650)); setStage(next); } await new Promise((r) => window.setTimeout(r, 450)); setStage("review_ready"); setGenerated(true); setStep(2); };
  const toggle = (episode: number) => setSelected((current) => current.includes(episode) ? current.filter((item) => item !== episode) : [...current, episode]);
  return <div className="app-shell"><aside className="demo-sidebar"><div className="demo-brand"><span className="brand-mark">✦</span><span>DramaClips</span><small>INTERACTIVE DEMO</small></div><div className="demo-nav">{nav.map(([key, label], i) => <button className={tab === key ? "active" : ""} onClick={() => setTab(key)} key={key}><span>0{i + 1}</span>{label}</button>)}{["Vizard", "Logs", "Storage"].map((name) => <button className="info-button" onClick={() => setModal(name)} key={name}>ⓘ {name} <small>what is this?</small></button>)}</div><div className="demo-footer"><span>RUOYA LI</span><small>Product engineer · system designer</small></div></aside><main className="demo-main"><header className="demo-topbar"><span>DRAMACLIPS / OPERATOR WORKSPACE</span><a href="/dramaclips.html">Read the case study ↗</a></header><section className="demo-heading"><div><p className="eyebrow">Interactive product demo</p><h1>From source<br/><em>to signal.</em></h1></div><p>Explore the workflow as an operator: shape source material into reviewed creative, prepare distribution, and inspect the audience signals that come back.</p></section><section className="demo-stage"><div className="stage-title"><div><p className="eyebrow">{tab === "library" ? "01 · Video asset library" : nav.find(([key]) => key === tab)?.[1]}</p><h2>{tab === "library" ? "Choose what to make" : tab === "hooks" ? "Create hooks" : tab === "publish" ? "Publish Center" : "Performance signals"}</h2></div><span className="demo-badge">{analytics?.mode === "demo" ? "DEMO DATA" : "LIVE"}</span></div><div className="flow-steps"><span className={step >= 1 ? "done" : ""}>1 Add drama</span><i>→</i><span className={step >= 2 ? "done" : ""}>2 Generate hook</span><i>→</i><span className={step >= 3 ? "done" : ""}>3 Publish</span></div>{tab === "library" && <Library added={added} onAdd={() => setModal("Add drama")} onOpen={() => { setTab("hooks"); setStep(2); }} />}{tab === "hooks" && <Hooks selected={selected} stage={stage} generated={generated} approved={approved} onToggle={toggle} onGenerate={generate} onApprove={() => setApproved(true)} onPublish={() => { setTab("publish"); setStep(3); }} />}{tab === "publish" && <Publish approved={approved} published={published} onPublish={() => { setPublished(true); setStep(3); }} />}{tab === "analytics" && <Analytics data={analytics} />}</section></main>{modal && <InfoModal title={modal} onClose={() => setModal(null)} onAction={modal === "Add drama" ? () => { setAdded(true); setModal(null); } : undefined} />}</div>;
}

function Library({ added, onAdd, onOpen }: { added: boolean; onAdd: () => void; onOpen: () => void }) { return <div className="library-panel"><div className="library-toolbar"><div className="library-stats"><b>29<small>dramas</small></b><b>151<small>hooks</small></b><b>6<small>platforms</small></b></div><button className="primary-action" onClick={onAdd}>+ Add drama</button></div>{added && <div className="drama-row selected-row"><span className="poster poster-neutral"/><div><b>Demo drama · onboarding complete</b><small>sample-source · 6 episodes</small></div><span className="status ready">Ready for hooks</span><button onClick={onOpen}>Open ↗</button></div>}<div className="drama-row selected-row"><span className="poster poster-one"/><div><b>Revenge of the Black Swan</b><small>revenge-of-the-black-swan</small></div><span className="status ready">Hooks ready</span><button onClick={onOpen}>Open ↗</button></div>{["They Fed Me to the Zombies, Not Knowing I Was Their Power", "He Chose Her, I Married the Mafia Don", "A Farm Girl's Reckoning"].map((name) => <div className="drama-row" key={name}><span className="poster poster-neutral"/><div><b>{name}</b><small>episode coverage · asset library</small></div><span className="status">Ready</span><button onClick={onOpen}>Open ↗</button></div>)}</div>; }

function Hooks({ selected, stage, generated, approved, onToggle, onGenerate, onApprove, onPublish }: { selected: number[]; stage: Stage; generated: boolean; approved: boolean; onToggle: (episode: number) => void; onGenerate: () => void; onApprove: () => void; onPublish: () => void }) { const current = stages.findIndex(([item]) => item === stage); return <div className="hooks-panel"><div className="selected-drama"><span className="poster poster-one"/><div><small>SELECTED DRAMA</small><b>Revenge of the Black Swan</b></div></div><p className="field-label">Episodes · select source material</p><div className="episode-grid">{Array.from({ length: 6 }, (_, i) => i + 1).map((episode) => <button className={selected.includes(episode) ? "episode selected" : "episode"} onClick={() => onToggle(episode)} key={episode}><span>{selected.includes(episode) ? "✓" : ""}</span>EP {episode}<small>{selected.includes(episode) ? "selected" : "available"}</small></button>)}</div><label className="field-label" htmlFor="direction">Advanced direction<textarea id="direction" defaultValue="Look for a clear emotional turn, relationship tension, or reveal. Keep the moment self-contained." /></label><button className="primary-action" disabled={!selected.length || (stage !== "idle" && stage !== "review_ready")} onClick={onGenerate}>{stage !== "idle" && stage !== "review_ready" ? "Generating…" : generated ? "↻ Run prepared demo again" : "✂ Generate & auto-save"}</button>{stage !== "idle" && <><div className="generation-timeline"><small>BUILT-IN PIPELINE · PREPARED ASSET DEMO</small>{stages.map(([item, label], i) => <span className={item === stage ? "current" : current > i ? "complete" : ""} key={item}>● {label}</span>)}</div><div className="processing-terminal"><div>[00:00.0] Job created · input validated</div><div>[00:00.5] Loading selected episode assets</div>{current >= 1 && <div>[00:02.1] Faster-Whisper · timestamped dialogue loaded · 842 words</div>}{current >= 2 && <div>[00:05.4] PySceneDetect · 18 scene boundaries · 42 windows</div>}{current >= 3 && <div>[00:07.0] Story signals + visual quality · duplicate removal</div>}{current >= 4 && <div>[00:08.7] FFmpeg · 1080×1920 · subtitles + cover frame · QA passed</div>}{stage === "review_ready" && <div>[00:10.0] Review-ready asset loaded · no production write</div>}</div></>}{generated && <SelectionExplainer approved={approved} onApprove={onApprove} onPublish={onPublish} />}</div>; }

function SelectionExplainer({ approved, onApprove, onPublish }: { approved: boolean; onApprove: () => void; onPublish: () => void }) { return <div className="selection-explainer"><div className="explainer-block"><p className="field-label">Candidate funnel</p><div className="funnel"><span>42 windows detected</span><span>31 dialogue-complete</span><span>18 emotional beats</span><span>12 direction-matched</span><span>8 visually viable</span><span>3 deduplicated finalists</span></div></div><div className="clip-grid">{clips.map((clip, index) => <div className="clip-card" key={clip}><video src={clip} controls preload="metadata" playsInline/><b>Candidate #{index + 1} · prepared clip</b><small>{index === 0 ? "0.87 · Conflict confrontation" : index === 1 ? "0.74 · Identity reveal" : "0.68 · Romantic tension"}</small></div>)}</div><div className="explainer-columns"><div><p className="field-label">Transcript + scene evidence</p><div className="evidence-card"><span>02:14–03:02 · EP 1 · Scene 07</span><p>“You knew the truth all along.”<br/>“I was trying to protect you.”</p><small>Clear confrontation · emotional turn · low context dependency</small></div><div className="scene-strip"><i/><i className="active"/><i/><i/><i/></div></div><div><p className="field-label">Candidate comparison</p><div className="comparison"><span><b>#1 · 0.87</b><small>Conflict confrontation · Low risk</small></span><span><b>#2 · 0.74</b><small>Identity reveal · Medium context risk</small></span><span><b>#3 · 0.68</b><small>Romantic tension · Lower visual score</small></span></div></div></div><details className="weighted-score" open><summary>Why Candidate #1 won · weighted score breakdown</summary><div className="score-list">{scores.map(([label, value, weight]) => <span key={label}><i>{label}</i><b>{value}</b><small>{weight}</small></span>)}</div><p className="selection-note">Strong conflict, clear emotional turn, visual continuity, and low context dependency. Candidate #2 ranked lower because it requires more previous-scene context.</p></details><div className="candidate-actions"><button className="primary-action" onClick={onApprove}>{approved ? "✓ Saved to R2 · approved" : "Approve & save to R2"}</button>{approved && <button className="text-action" onClick={onPublish}>Use approved asset in Publish Center ↗</button>}</div></div>; }

function Publish({ approved, published, onPublish }: { approved: boolean; published: boolean; onPublish: () => void }) { return <div className="publish-panel"><div className="publish-grid"><div><p className="field-label">01 · Exact video asset</p><div className="asset-card"><b>Saved hook · EP 1</b><small>Prepared generated clip · 16.9s</small><span className="status ready">{approved ? "Approved · saved to R2" : "Awaiting approval"}</span></div></div><div><p className="field-label">02 · Choose delivery</p><div className="delivery-card"><b>{published ? "Published successfully" : "Schedule publish"}</b><small>One workflow for TikTok, Instagram, YouTube, and Facebook.</small><div className="platforms"><span>✓ TikTok</span><span>✓ Instagram</span><span>✓ YouTube</span><span>✓ Facebook</span></div><button className="primary-action" disabled={!approved} onClick={onPublish}>{published ? "✓ Published · Confirmed" : approved ? "Schedule publish" : "Approve a hook first"}</button></div></div></div></div>; }

function InfoModal({ title, onClose, onAction }: { title: string; onClose: () => void; onAction?: () => void }) { const copy: Record<string, [string, string]> = { "Add drama": ["Content onboarding", "Collect metadata and source episodes. Production uses signed upload URLs and sends media directly to Cloudflare R2."], Vizard: ["Optional clipping provider", "Vizard is a downstream third-party clipping path. Built-in generation remains the core workflow."], Logs: ["Operational visibility", "Logs expose async progress, retries, provider responses, and failures."], Storage: ["Data and media boundaries", "Supabase stores workflow state and Cloudflare R2 stores durable media. This is a prepared public demo."] }; const [heading, body] = copy[title] ?? [title, "This module is represented as a read-only demo."]; return <div className="modal-backdrop" onClick={onClose}><div className="info-modal" onClick={(e) => e.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button><p className="eyebrow">System note</p><h3>{heading}</h3><p>{body}</p><button className="primary-action" onClick={onAction ?? onClose}>{onAction ? "Add demo drama" : "Got it"}</button></div></div>; }

function Analytics({ data }: { data: { mode: string; updatedAt: string; metrics: Record<string, number>; daily: number[] } | null }) { const labels: Record<string, string> = { publishedAssets: "Published assets", approvedHooks: "Approved hooks", trackedVisits: "Tracked visits", codeCopies: "Code copies", rsRedirects: "RS redirects" }; return <div className="analytics-panel"><div className="metric-grid">{Object.entries(data?.metrics ?? {}).map(([key, value]) => <div className="metric" key={key}><small>{labels[key] ?? key}</small><b>{value.toLocaleString()}</b><span>↑ today</span></div>)}</div><div className="chart-card"><b>Audience flow</b><small>Representative demo data</small><div className="bars">{(data?.daily ?? []).map((value, i) => <span style={{ height: `${Math.max(16, value / 2)}px` }} key={i}><i>{value}</i></span>)}</div></div></div>; }
